export { default as Header } from "./header"
export { default as Layout } from "./layout"
export { default as SEO } from "./seo"
export { default as Jumbo } from "./Jumbo"
export { default as AboutComp } from "./AboutComp"
export { default as PortfolioComp } from "./PortfolioComp"
